{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/workspace/home/user/Documents/Github/6.S890_Course_Project/src",
    "dependencies": [
      "numpy==1.24.4",
      "PyYAML==5.3.1",
      "sacred==0.8.7",
      "torch==2.4.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [
      {
        "commit": "51b5ae199159c387a6ae750d846bbcffa3f49b29",
        "dirty": false,
        "url": "https://github.com/srcJin/6.S890_Course_Project.git"
      },
      {
        "commit": "51b5ae199159c387a6ae750d846bbcffa3f49b29",
        "dirty": false,
        "url": "https://github.com/srcJin/6.S890_Course_Project.git"
      },
      {
        "commit": "51b5ae199159c387a6ae750d846bbcffa3f49b29",
        "dirty": false,
        "url": "https://github.com/srcJin/6.S890_Course_Project.git"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources/main_10071cd35b239d4d9d6b06262697f6b3.py"
      ],
      [
        "run.py",
        "_sources/run_d62d3087da7829de8e4bcdca6986827e.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_836123fa54ffb6ffe3010ba48531394a.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"src/main.py\", line 45, in my_main\n    run(_run, config, _log)\n",
    "  File \"/workspace/home/user/Documents/Github/6.S890_Course_Project/src/run.py\", line 74, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"/workspace/home/user/Documents/Github/6.S890_Course_Project/src/run.py\", line 224, in run_sequential\n    learner.train(episode_sample, runner.t_env, episode)\n",
    "  File \"/workspace/home/user/Documents/Github/6.S890_Course_Project/src/learners/actor_critic_pac_dcg_learner.py\", line 64, in train\n    advantages, critic_train_stats = self.train_critic_sequential(\n",
    "  File \"/workspace/home/user/Documents/Github/6.S890_Course_Project/src/learners/actor_critic_pac_dcg_learner.py\", line 146, in train_critic_sequential\n    v = self.state_value(batch)[:, :-1].squeeze(3)\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1553, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1562, in _call_impl\n    return forward_call(*args, **kwargs)\n",
    "  File \"/workspace/home/user/Documents/Github/6.S890_Course_Project/src/modules/critics/centralV_ns.py\", line 29, in forward\n    q = self.critics[i](inputs)\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1553, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1562, in _call_impl\n    return forward_call(*args, **kwargs)\n",
    "  File \"/workspace/home/user/Documents/Github/6.S890_Course_Project/src/modules/critics/mlp.py\", line 13, in forward\n    x = F.relu(self.fc1(inputs))\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1553, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1562, in _call_impl\n    return forward_call(*args, **kwargs)\n",
    "  File \"/home/user/miniconda3/envs/epymarl/lib/python3.8/site-packages/torch/nn/modules/linear.py\", line 117, in forward\n    return F.linear(input, self.weight, self.bias)\n",
    "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)\n"
  ],
  "heartbeat": "2024-12-11T07:06:13.554695",
  "host": {
    "ENV": {},
    "cpu": "AMD Ryzen Threadripper PRO 5955WX 16-Cores",
    "gpus": {
      "driver_version": "560.35.03",
      "gpus": [
        {
          "model": "NVIDIA GeForce RTX 4090",
          "persistence_mode": true,
          "total_memory": 24564
        },
        {
          "model": "NVIDIA GeForce RTX 4090",
          "persistence_mode": true,
          "total_memory": 24564
        }
      ]
    },
    "hostname": "0ecbe9360acb",
    "os": [
      "Linux",
      "Linux-5.15.0-124-generic-x86_64-with-glibc2.17"
    ],
    "python_version": "3.8.20"
  },
  "meta": {
    "command": "my_main",
    "config_updates": {},
    "named_configs": [],
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--id": null,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-12-11T07:06:06.267158",
  "status": "FAILED",
  "stop_time": "2024-12-11T07:06:13.558247"
}